events {}

http {
    upstream backend {
        server 10.2.0.8:18789;
    }
    upstream game {
        server app:14527;
    }
    server {
        listen 443 ssl;
        server_name claw.cx233.xyz;

        ssl_certificate /etc/nginx/cert/game.pem;
        ssl_certificate_key /etc/nginx/cert/game.key;

        location / {
            proxy_pass http://backend;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
       server {
            listen 880 ssl;
            server_name game.cx233.xyz;

            ssl_certificate /etc/nginx/cert/game.pem;
            ssl_certificate_key /etc/nginx/cert/game.key;

            location / {
                proxy_pass http://game;
                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
}
